apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dtyq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dtyq
    app.kubernetes.io/part-of: byoc-app-uzoq
  name: dtyq
spec:
  rules:
  - host: dtyq-byoc-crjw-tenant.apps.efa375eb7f8cf5447f9e.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: dtyq
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
